# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[6, 5, 7, 5, 8, 1, 0, 6, 4, 3, 0, 2],
       [1, 0, 6, 6, 9, 5, 5, 6, 3, 0, 0, 9],
       [1, 1, 4, 9, 9, 8, 0, 7, 0, 5, 7, 9],
       [8, 3, 3, 9, 6, 1, 1, 4, 4, 2, 1, 1],
       [5, 1, 9, 5, 1, 0, 2, 7, 4, 8, 8, 4],
       [4, 8, 1, 1, 3, 4, 4, 9, 8, 9, 6, 1],
       [6, 5, 2, 5, 1, 6, 2, 3, 4, 2, 6, 4],
       [9, 3, 5, 9, 1, 9, 8, 0, 8, 2, 3, 6],
       [4, 9, 4, 8, 1, 1, 0, 2, 0, 8, 9, 0],
       [5, 3, 5, 1, 4, 1, 4, 1, 8, 1, 4, 7],
       [3, 2, 2, 3, 5, 1, 8, 8, 5, 6, 8, 6],
       [1, 4, 6, 7, 8, 7, 8, 3, 4, 3, 7, 2]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

<ipython-input-9-6137fcb8b1c2>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[6, 5, 7, 5, 8, 1, 0, 6, 4, 3, 0, 2],
       [1, 0, 6, 6, 9, 5, 5, 6, 3, 0, 0, 9],
       [1, 1, 4, 9, 9, 8, 0, 7, 0, 5, 7, 9],
       [8, 3, 3, 9, 6, 1, 1, 4, 4, 2, 1, 1],
       [5, 1, 9, 5, 1, 0, 2, 7, 4, 8, 8, 4],
       [4, 8, 1, 1, 3, 4, 4, 9, 8, 9, 6, 1],
       [6, 5, 2, 5, 1, 6, 2, 3, 4, 2, 6, 4],
       [9, 3, 5, 9, 1, 9, 8, 0, 8, 2, 3, 6],
       [4, 9, 4, 8, 1, 1, 0, 2, 0, 8, 9, 0],
       [5, 3, 5, 1, 4, 1, 4, 1, 8, 1, 4, 7],
       [3, 2, 2, 3, 5, 1, 8, 8, 5, 6, 8, 6],
       [1, 4, 6, 7, 8, 7, 8, 3, 4, 3, 7, 2]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -13,   7,  -5,   8,  -3,   9,   3,   2, -11, -16,   0],
       [  0,  -4,  -3,   8,   4,  17, -21,  18, -19,  11,  13,   0],
       [  0,  -1, -13,  13,   4, -11,  -3,  -3,   6, -10, -14,   0],
       [  0, -21,  26,   0, -10,  -8,  -4,   9, -11,   9,  13,   0],
       [  0,  21, -16, -10,   5,   3,  -1,  14,   6,  12,   0,   0],
       [  0,   1,  -8,   7, -11,   8, -13,  -3,  -5, -13,   9,   0],
       [  0, -16,   2,  17, -16,  20,  21, -21,  26, -13, -11,   0],
       [  0,  22, -11,  17, -10,  -7, -15,   7, -26,  20,  21,   0],
       [  0,  -9,  10, -16,   8,  -6,   6, -18,  25, -22,  -9,   0],
       [  0,  -4,  -8,  -3,   4, -17,  11,  15,  -6,   7,   9,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [18]:
l=1
kernel = np.array([[0,-1,0], [-1,5,-1], [0,-1,0]],np.float32)

In [19]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [20]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [21]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()